conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main

MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - '10.11'                # [osx and x86_64]
macos_min_version:         # [osx and x86_64]
  - '10.11'                # [osx and x86_64]
